[package]
name = "gump-agent"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
gump-types = { workspace = true }
gump-driver = { workspace = true }
gump-hiccup = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
